name: bd_offline_geocoder_example
description: Flutter example app for bd_offline_geocoder.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  bd_offline_geocoder:
    path: ../../packages/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
